=== TotalPotatoes/GameMain/CardGame/src/CardGame/cards.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cardList (card)>
<!ELEMENT card (name, cardType, castTime, resource, costB, costW, costG, costN)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT cardType (#PCDATA)>
<!ELEMENT castTime (#PCDATA)>
<!ELEMENT resource (#PCDATA)>
<!ELEMENT costB (#PCDATA)>
<!ELEMENT costW (#PCDATA)>
<!ELEMENT costG (#PCDATA)>
<!ELEMENT costN (#PCDATA)>

=== TotalPotatoes/GameMain/CardGame/src/CardGame/cardData.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE roles SYSTEM "cards.dtd">
<cardList>
	<card>
    		<name>Default 1</name>
		<cardType>SUMMON</cardType>
    		<castTime>10</castTime>
		<resource>false</resource>
    		<costB>1</costB>
    		<costW>1</costW>
    		<costG>1</costG>
    		<costN>1</costN>
    	</card>
</cardList>
